require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomSearchEnginesController do

  # This should return the minimal set of attributes required to create a valid
  # CustomSearchEngine. As you add validations to CustomSearchEngine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomSearchEnginesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all custom_search_engines as @custom_search_engines" do
      custom_search_engine = CustomSearchEngine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:custom_search_engines).should eq([custom_search_engine])
    end
  end

  describe "GET show" do
    it "assigns the requested custom_search_engine as @custom_search_engine" do
      custom_search_engine = CustomSearchEngine.create! valid_attributes
      get :show, {:id => custom_search_engine.to_param}, valid_session
      assigns(:custom_search_engine).should eq(custom_search_engine)
    end
  end

  describe "GET new" do
    it "assigns a new custom_search_engine as @custom_search_engine" do
      get :new, {}, valid_session
      assigns(:custom_search_engine).should be_a_new(CustomSearchEngine)
    end
  end

  describe "GET edit" do
    it "assigns the requested custom_search_engine as @custom_search_engine" do
      custom_search_engine = CustomSearchEngine.create! valid_attributes
      get :edit, {:id => custom_search_engine.to_param}, valid_session
      assigns(:custom_search_engine).should eq(custom_search_engine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomSearchEngine" do
        expect {
          post :create, {:custom_search_engine => valid_attributes}, valid_session
        }.to change(CustomSearchEngine, :count).by(1)
      end

      it "assigns a newly created custom_search_engine as @custom_search_engine" do
        post :create, {:custom_search_engine => valid_attributes}, valid_session
        assigns(:custom_search_engine).should be_a(CustomSearchEngine)
        assigns(:custom_search_engine).should be_persisted
      end

      it "redirects to the created custom_search_engine" do
        post :create, {:custom_search_engine => valid_attributes}, valid_session
        response.should redirect_to(CustomSearchEngine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved custom_search_engine as @custom_search_engine" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomSearchEngine.any_instance.stub(:save).and_return(false)
        post :create, {:custom_search_engine => {}}, valid_session
        assigns(:custom_search_engine).should be_a_new(CustomSearchEngine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomSearchEngine.any_instance.stub(:save).and_return(false)
        post :create, {:custom_search_engine => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested custom_search_engine" do
        custom_search_engine = CustomSearchEngine.create! valid_attributes
        # Assuming there are no other custom_search_engines in the database, this
        # specifies that the CustomSearchEngine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomSearchEngine.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => custom_search_engine.to_param, :custom_search_engine => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested custom_search_engine as @custom_search_engine" do
        custom_search_engine = CustomSearchEngine.create! valid_attributes
        put :update, {:id => custom_search_engine.to_param, :custom_search_engine => valid_attributes}, valid_session
        assigns(:custom_search_engine).should eq(custom_search_engine)
      end

      it "redirects to the custom_search_engine" do
        custom_search_engine = CustomSearchEngine.create! valid_attributes
        put :update, {:id => custom_search_engine.to_param, :custom_search_engine => valid_attributes}, valid_session
        response.should redirect_to(custom_search_engine)
      end
    end

    describe "with invalid params" do
      it "assigns the custom_search_engine as @custom_search_engine" do
        custom_search_engine = CustomSearchEngine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomSearchEngine.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_search_engine.to_param, :custom_search_engine => {}}, valid_session
        assigns(:custom_search_engine).should eq(custom_search_engine)
      end

      it "re-renders the 'edit' template" do
        custom_search_engine = CustomSearchEngine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomSearchEngine.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_search_engine.to_param, :custom_search_engine => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested custom_search_engine" do
      custom_search_engine = CustomSearchEngine.create! valid_attributes
      expect {
        delete :destroy, {:id => custom_search_engine.to_param}, valid_session
      }.to change(CustomSearchEngine, :count).by(-1)
    end

    it "redirects to the custom_search_engines list" do
      custom_search_engine = CustomSearchEngine.create! valid_attributes
      delete :destroy, {:id => custom_search_engine.to_param}, valid_session
      response.should redirect_to(custom_search_engines_url)
    end
  end

end
